# Entregable 1

**Diego Yael Islas Santoyo**

### Cargar las tablas de datos en Pandas:

In [2]:
import pandas as pd
df_calendar = pd.read_excel('DIM_CALENDAR (2).xlsx')
df_calendar

      WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0    01-21  2021      1            1 2021-01-10
1    02-21  2021      1            2 2021-01-17
2    03-21  2021      1            3 2021-01-24
3    04-21  2021      1            4 2021-01-31
4    05-21  2021      2            5 2021-02-07
..     ...   ...    ...          ...        ...
151  48-23  2023     12           48 2023-12-04
152  49-23  2023     12           49 2023-12-11
153  50-23  2023     12           50 2023-12-18
154  51-23  2023     12           51 2023-12-25
155  52-23  2023      1           52 2024-01-01

[156 rows x 5 columns]

In [4]:
df_category = pd.read_csv('DIM_CATEGORY (2).csv')
df_category

   ID_CATEGORY                        CATEGORY
0            1  FABRIC TREATMENT and SANIT\r\n
1            2                       AIR CARE
2            3                    LAVAVAJILLAS
3            4                MEGA SUPERFICIES
4            5             LAVATORY CARE & BRC

In [6]:
df_product = pd.read_excel('DIM_PRODUCT (1).xlsx')
df_product

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
...,...,...,...,...,...,...,...,...,...
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA
501,INDS. ALEN,CLORALEX,7501025412142,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
502,INDS. ALEN,CLORALEX,NaN,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
503,CLOROX,CLOROX,NaN,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [8]:
df_segment = pd.read_excel('DIM_SEGMENT (1).xlsx')
df_segment

,CATEGORY,ATTR1,ATTR2,ATTR3,FORMAT,SEGMENT
0,1,CLORO,CLORO,BAMBINO,LIQUIDO,BLEACH
1,1,CLORO,CLORO,GERMICIDA,LIQUIDO,BLEACH
2,1,CLORO,CLORO,MASCOTAS,LIQUIDO,BLEACH
3,1,CLORO,CLORO,MULTIUSOS,GEL,BLEACH
4,1,CLORO,CLORO,MULTIUSOS,LIQUIDO,BLEACH
5,1,CLORO,CLORO,NO DEFINIDO,LIQUIDO,BLEACH
6,1,CLORO,CLORO,NO DEFINIDO,POLVO,BLEACH
7,1,CLORO,CLORO,OTR. TIPOS,LIQUIDO,BLEACH
8,1,CLORO,CLORO,OTR. TIPOS,POLVO,BLEACH
9,1,CLORO,CLORO,ROPA BEBE,LIQUIDO,BLEACH
10,1,CLORO,CLORO,NaN,LIQUIDO,BLEACH
11,1,CLORO,MASCOTAS,MASCOTAS,LIQUIDO,BLEACH
12,1,CLORO,MULTIUSOS,MULTIUSOS,GEL,BLEACH
13,1,CLORO,NO DEFINIDO,NO DEFINIDO,LIQUIDO,BLEACH
14,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,GEL,LIQUID & GEL
15,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,POLVO,POWDER
16,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,TOALLAS,OTHERS
17,1,PRELAVADOR,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,PRETREAT
18,1,PRELAVADOR,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRETREAT
19,1,PRELAVADOR,FABRIC TREATMENT,PRE LAVADOR,POLVO,POWDER
20,1,PRELAVADOR,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,PRETREAT
21,1,PRELAVADOR,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,PRETREAT
22,1,PRELAVADOR,FABRIC TREATMENT,ROSA,GEL,LIQUID & GEL
23,1,PRELAVADOR,FABRIC TREATMENT,ROSA,LIQUIDO,PRETREAT
24,1,PRELAVADOR,FABRIC TREATMENT,ROSA,POLVO,POWDER
25,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,BARRA,BAR
26,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,GEL,LIQUID & GEL
27,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,LIQUIDO,LIQUID & GEL
28,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,POLVO,POWDER
29,1,SAFE BLEACH,FABRIC TREATMENT,COLOR PODER VINAGRE,GEL,LIQUID & GEL
30,1,SAFE BLEACH,FABRIC TREATMENT,COLOR PODER VINAGRE,LIQUIDO,LIQUID & GEL
31,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,BARRA,BAR
32,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,GEL,LIQUID & GEL
33,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,LIQUID & GEL
34,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,POLVO,POWDER
35,1,SAFE BLEACH,FABRIC TREATMENT,PODER OXIGENO,GEL,LIQUID & GEL
36,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BARRA,BAR
37,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,GEL,LIQUID & GEL
38,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRETREAT
39,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,POLVO,POWDER
40,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,GEL,LIQUID & GEL
41,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,LIQUID & GEL
42,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,POLVO,POWDER
43,1,SAFE BLEACH,FABRIC TREATMENT,ROPA BLANCA,LIQUIDO,LIQUID & GEL
44,1,SAFE BLEACH,FABRIC TREATMENT,ROPA BLANCA,POLVO,POWDER
45,1,SAFE BLEACH,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,LIQUID & GEL
46,1,SAFE BLEACH,FABRIC TREATMENT,ROPA COLOR,POLVO,POWDER
47,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,BARRA,BAR
48,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,GEL,LIQUID & GEL
49,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,LIQUIDO,LIQUID & GEL
50,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,POLVO,POWDER
51,1,SAFE BLEACH,PRE LAVADOR,PRE LAVADOR,GEL,PRETREAT
52,1,SANITIZANTE,SANITIZANTE,SANITIZANTE,LIQUIDO,SANITIZER

##### Revisar y entender los datos cargados:

In [10]:
# 1era revisión del primer archivo con head(), info() y describe()
df_calendar.head(5)

    WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0  01-21  2021      1            1 2021-01-10
1  02-21  2021      1            2 2021-01-17
2  03-21  2021      1            3 2021-01-24
3  04-21  2021      1            4 2021-01-31
4  05-21  2021      2            5 2021-02-07

In [12]:
df_calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WEEK         156 non-null    object
 1   YEAR         156 non-null    int64
 2   MONTH        156 non-null    int64
 3   WEEK_NUMBER  156 non-null    int64
 4   DATE         156 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 6.2+ KB

In [14]:
df_calendar.describe()

              YEAR       MONTH  WEEK_NUMBER                 DATE
count   156.000000  156.000000   156.000000                  156
mean   2022.000000    6.487179    26.500000  2022-07-06 20:00:00
min    2021.000000    1.000000     1.000000  2021-01-10 00:00:00
25%    2021.000000    3.750000    13.750000  2021-10-08 06:00:00
50%    2022.000000    6.500000    26.500000  2022-07-06 12:00:00
75%    2023.000000    9.250000    39.250000  2023-04-04 18:00:00
max    2023.000000   12.000000    52.000000  2024-01-01 00:00:00
std       0.819126    3.459419    15.056667                  NaN

In [16]:
# 2da revisión del primer archivo con head(), info() y describe()
df_category.head(5)

   ID_CATEGORY                        CATEGORY
0            1  FABRIC TREATMENT and SANIT\r\n
1            2                       AIR CARE
2            3                    LAVAVAJILLAS
3            4                MEGA SUPERFICIES
4            5             LAVATORY CARE & BRC

In [18]:
df_category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_CATEGORY  5 non-null      int64
 1   CATEGORY     5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [20]:
df_category.describe()

       ID_CATEGORY
count     5.000000
mean      3.000000
std       1.581139
min       1.000000
25%       2.000000
50%       3.000000
75%       4.000000
max       5.000000

In [22]:
# 3ra revisión del primer archivo con head(), info() y describe()
df_product.head(5)

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [24]:
df_product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MANUFACTURER      505 non-null    object
 1   BRAND             505 non-null    object
 2   ITEM              503 non-null    object
 3   ITEM_DESCRIPTION  505 non-null    object
 4   CATEGORY          505 non-null    int64
 5   FORMAT            505 non-null    object
 6   ATTR1             499 non-null    object
 7   ATTR2             505 non-null    object
 8   ATTR3             499 non-null    object
dtypes: int64(1), object(8)
memory usage: 35.6+ KB

In [26]:
df_product.describe()

       CATEGORY
count     505.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0

In [28]:
# 4ta revisión del primer archivo con head(), info() y describe()
df_segment.head(5)

   CATEGORY  ATTR1  ATTR2      ATTR3   FORMAT SEGMENT
0         1  CLORO  CLORO    BAMBINO  LIQUIDO  BLEACH
1         1  CLORO  CLORO  GERMICIDA  LIQUIDO  BLEACH
2         1  CLORO  CLORO   MASCOTAS  LIQUIDO  BLEACH
3         1  CLORO  CLORO  MULTIUSOS      GEL  BLEACH
4         1  CLORO  CLORO  MULTIUSOS  LIQUIDO  BLEACH

In [30]:
df_segment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CATEGORY  53 non-null     int64
 1   ATTR1     53 non-null     object
 2   ATTR2     53 non-null     object
 3   ATTR3     52 non-null     object
 4   FORMAT    53 non-null     object
 5   SEGMENT   53 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.6+ KB

In [32]:
df_segment.describe()

       CATEGORY
count      53.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0

### Realizar la limpieza de datos

In [34]:
#1era limpieza
df_calendar.columns

Index(['WEEK', 'YEAR', 'MONTH', 'WEEK_NUMBER', 'DATE'], dtype='object')

In [36]:
df_calendar['WEEK'].unique()

array(['01-21', '02-21', '03-21', '04-21', '05-21', '06-21', '07-21',
       '08-21', '09-21', '10-21', '11-21', '12-21', '13-21', '14-21',
       '15-21', '16-21', '17-21', '18-21', '19-21', '20-21', '21-21',
       '22-21', '23-21', '24-21', '25-21', '26-21', '27-21', '28-21',
       '29-21', '30-21', '31-21', '32-21', '33-21', '34-21', '35-21',
       '36-21', '37-21', '38-21', '39-21', '40-21', '41-21', '42-21',
       '43-21', '44-21', '45-21', '46-21', '47-21', '48-21', '49-21',
       '50-21', '51-21', '52-21', '01-22', '02-22', '03-22', '04-22',
       '05-22', '06-22', '07-22', '08-22', '09-22', '10-22', '11-22',
       '12-22', '13-22', '14-22', '15-22', '16-22', '17-22', '18-22',
       '19-22', '20-22', '21-22', '22-22', '23-22', '24-22', '25-22',
       '26-22', '27-22', '28-22', '29-22', '30-22', '31-22', '32-22',
       '33-22', '34-22', '35-22', '36-22', '37-22', '38-22', '39-22',
       '40-22', '41-22', '42-22', '43-22', '44-22', '45-22', '46-22',
       '47-22', '48-22', '49-22', '50-22', '51-22', '52-22', '01-23',
       '02-23', '03-23', '04-23', '05-23', '06-23', '07-23', '08-23',
       '09-23', '10-23', '11-23', '12-23', '13-23', '14-23', '15-23',
       '16-23', '17-23', '18-23', '19-23', '20-23', '21-23', '22-23',
       '23-23', '24-23', '25-23', '26-23', '27-23', '28-23', '29-23',
       '30-23', '31-23', '32-23', '33-23', '34-23', '35-23', '36-23',
       '37-23', '38-23', '39-23', '40-23', '41-23', '42-23', '43-23',
       '44-23', '45-23', '46-23', '47-23', '48-23', '49-23', '50-23',
       '51-23', '52-23'], dtype=object)

In [38]:
df_calendar['YEAR'].unique()

array([2021, 2022, 2023], dtype=int64)

In [40]:
df_calendar['MONTH'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [42]:
df_calendar['WEEK_NUMBER'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52], dtype=int64)

In [44]:
df_calendar['DATE'].unique()

<DatetimeArray>
['2021-01-10 00:00:00', '2021-01-17 00:00:00', '2021-01-24 00:00:00',
 '2021-01-31 00:00:00', '2021-02-07 00:00:00', '2021-02-14 00:00:00',
 '2021-02-21 00:00:00', '2021-02-28 00:00:00', '2021-03-07 00:00:00',
 '2021-03-14 00:00:00',
 ...
 '2023-10-30 00:00:00', '2023-11-06 00:00:00', '2023-11-13 00:00:00',
 '2023-11-20 00:00:00', '2023-11-27 00:00:00', '2023-12-04 00:00:00',
 '2023-12-11 00:00:00', '2023-12-18 00:00:00', '2023-12-25 00:00:00',
 '2024-01-01 00:00:00']
Length: 156, dtype: datetime64[ns]

In [46]:
df_calendar.isnull().sum()

WEEK           0
YEAR           0
MONTH          0
WEEK_NUMBER    0
DATE           0
dtype: int64

In [48]:
df_calendar.dtypes

WEEK                   object
YEAR                    int64
MONTH                   int64
WEEK_NUMBER             int64
DATE           datetime64[ns]
dtype: object

In [50]:
df_calendar.duplicated().sum()

0

In [52]:
df_calendar = df_calendar.drop_duplicates()

In [54]:
df_calendar = df_calendar.sort_values('DATE', ascending= True)
df_calendar

      WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0    01-21  2021      1            1 2021-01-10
1    02-21  2021      1            2 2021-01-17
2    03-21  2021      1            3 2021-01-24
3    04-21  2021      1            4 2021-01-31
4    05-21  2021      2            5 2021-02-07
..     ...   ...    ...          ...        ...
151  48-23  2023     12           48 2023-12-04
152  49-23  2023     12           49 2023-12-11
153  50-23  2023     12           50 2023-12-18
154  51-23  2023     12           51 2023-12-25
155  52-23  2023      1           52 2024-01-01

[156 rows x 5 columns]

**El archivo df_calendar al parecer no presenta ningun tipo de duplicado, ni datos duplicados o errores tipograficos.**

In [56]:
#2da limpieza
df_category.columns

Index(['ID_CATEGORY', 'CATEGORY'], dtype='object')

In [58]:
df_category['ID_CATEGORY'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [60]:
df_category['CATEGORY'].unique()

array(['FABRIC TREATMENT and SANIT\r\n', 'AIR CARE ', 'LAVAVAJILLAS',
       'MEGA SUPERFICIES', 'LAVATORY CARE & BRC'], dtype=object)

In [62]:
df_category['CATEGORY'] = df_category['CATEGORY'].replace({'FABRIC TREATMENT and SANIT\r\n': 'FABRIC TREATMENT AND SANIT'})
df_category.head(5)

   ID_CATEGORY                    CATEGORY
0            1  FABRIC TREATMENT AND SANIT
1            2                   AIR CARE
2            3                LAVAVAJILLAS
3            4            MEGA SUPERFICIES
4            5         LAVATORY CARE & BRC

In [64]:
df_category.isnull().sum()

ID_CATEGORY    0
CATEGORY       0
dtype: int64

In [66]:
df_category.dtypes

ID_CATEGORY     int64
CATEGORY       object
dtype: object

In [68]:
df_category.duplicated().sum()

0

In [70]:
df_category = df_category.drop_duplicates()

In [72]:
df_category = df_category.sort_values('CATEGORY', ascending=True)
df_category

   ID_CATEGORY                    CATEGORY
1            2                   AIR CARE
0            1  FABRIC TREATMENT AND SANIT
4            5         LAVATORY CARE & BRC
2            3                LAVAVAJILLAS
3            4            MEGA SUPERFICIES

**En el archivo de df_category presentó solamente unos errores ortograficos**

In [74]:
#3ra limpieza 
df_product.columns

Index(['MANUFACTURER', 'BRAND', 'ITEM', 'ITEM_DESCRIPTION', 'CATEGORY',
       'FORMAT', 'ATTR1', 'ATTR2', 'ATTR3'],
      dtype='object')

In [76]:
df_product['MANUFACTURER'].unique()

array(['INDS. ALEN', 'QUIMICA GONCAL', 'RECKITT', 'P&G',
       'OTHERS FABRICANTE UNIF.', 'ARTIC WHITE', 'CLOROX', 'SC JOHNSON',
       'WHITE MAGIC', 'FAB. DE JABON LA REINERA', 'CLARASOL',
       'CHURCH & DWIGHT', 'GRUPO AC MARCAS', 'DELTA PRONATURA',
       'INDS. H24', 'LA CORONA', 'LA JAPONESA', 'BLANQUEADORA MEXICANA',
       'JABONERA LA ESPUMA', 'IBERIA'], dtype=object)

In [78]:
df_product['BRAND'].unique()

array(['CLORALEX', 'PATITO', 'LYSOL', 'TIDE', 'OTHERS MARCA UNIF.',
       'ARTIC WHITE', 'CLOROX', 'SHOUT', 'WHITE MAGIC', 'MARIPOSA',
       'CLARASOL', 'OXI CLEAN', 'SANYTOL', 'DR.BECKMANN',
       'CUELLOS PUNOS Y MANCHITAS', 'RADIANTE', 'CLORALUZ', 'BLANCATEL',
       'CARISMA', 'PURO SOL', 'CLORTEX', 'LA JAPONESA', 'CLORO 10',
       'VANISH PODER 02', 'VANISH', 'HARPIC', 'VANISH CRYSTAL WHITE',
       'VANISH EXTRA HIGIENE', 'LA VALENCIANA', 'LOS PATITOS', 'BANDERA',
       'BCLORHADA', 'IBERIA'], dtype=object)

In [80]:
df_product['ITEM'].unique()

array(['0000075000592', '0000075000608', '0000075000615', '0000075000622',
       '0000075000639', '0000075000646', '0000075000653', '0000075000677',
       '0000075000684', '0000075010539', '0019200958714', '0037000018704',
       '0037000213215', '0037000830870', '0037000889281', '0041380309109',
       '0041380309116', '0041596020959', '0043152007114', '0044600002033',
       '0044600016924', '0044600305974', '0044600306414', '0044600312804',
       '0044600313429', '0044600313436', '0044600313719', '0046500022517',
       '0046500022692', '0046500022746', '0046500222979', '0046500729355',
       '0048155906310', '0079893431208', '0123456808218', '0602925200017',
       '0602925200031', '0612464080148', '0616533000525', '0616533000532',
       '0722429128034', '0732913227013', '0737128047005', '0737128127004',
       '0737128247009', '0741120000005', '0741120000012', '0741120000029',
       '0741120000036', '0741120000746', '0741120010011', '0757037000489',
       '0757037512449', '0757037513552', '0757037514016BP1',
       '0757037516935', '0757037517123', '0757037517499', '0757037517611',
       '3045200760009', '3045206360609', '3045206382007', '4008455394015',
       '4008455394114', '4008455394213', '4008455394411', '4008455394510',
       '4008455394619', '4008455423517', '4008455423616', '4008455423715',
       '4008455425412', '4008455427614', '4008455438016', '4008455457512',
       '4008455457710', '4008455458618', '4008455458717', '4008455459417',
       '4008455460215', '4008455476711', '4008455524917', '4008455567013',
       '7501021160689', '7501021160719', '7501021160726', '7501025400323',
       '7501025400330', '7501025400347', '7501025400354', '7501025400361',
       '7501025400378', '7501025400385', '7501025400392', '7501025400408',
       '7501025400415', '7501025400422', '7501025400439', '7501025400767',
       '7501025400781', '7501025400903', '7501025400927', '7501025400941',
       '7501025400958', '7501025400965', '7501025400989', '7501025400996',
       '7501025401023', '7501025401047', '7501025401061', '7501025401078',
       '7501025401115', '7501025401122', '7501025401252', '7501025401306',
       '7501025401313', '7501025401511', '7501025401528', '7501025401535',
       '7501025401566', '7501025401573', '7501025401580',
       '7501025401597BP1', '7501025401641', '7501025401795',
       '7501025401801', '7501025401832', '7501025401849', '7501025401856',
       '7501025401863', '7501025401887', '7501025401894', '7501025401900',
       '7501025401917', '7501025401931', '7501025401948', '7501025401993',
       '7501025402037', '7501025402051', '7501025402082', '7501025402211',
       '7501025402235', '7501025402242', '7501025402259', '7501025402303',
       '7501025402440', '7501025402990', '7501025403423', '7501025405076',
       '7501025405090', '7501025405106', '7501025405120', '7501025405151',
       '7501025405205', '7501025405212', '7501025405229', '7501025405236',
       '7501025405274', '7501025405298BP2', '7501025405311',
       '7501025405816', '7501025405885', '7501025406561', '7501025406578',
       '7501025408404', '7501025408947', '7501025409104', '7501025409470',
       '7501025410834', '7501025411893', '7501025411978', '7501025411992',
       '7501025412005', '7501025412012', '7501025412104', '7501025412135',
       '7501025412357', '7501025412401', '7501025412418', '7501025412463',
       '7501025412784', '7501025418106', '7501025441319BP2',
       '7501025441326BP2', '7501025441357BP1', '7501025441463BP2',
       '7501025441487BP1', '7501025441487BP2', '7501025450212',
       '7501025450274', '7501025450618BP1', '7501025450618BP2',
       '7501025450632', '7501025450984', '7501025450984BP1',
       '7501025450984BP2', '7501025454012', '7501025454029',
       '7501025459208', '7501026005800', '7501026030109', '7501041505309',
       '7501041508652', '7501042300033', '7501042300057', '7501042301733',
       '7501042301740', '7501042301757', '7501042301764', '7501042301771',
       '7501042301788', '7501042302556', '7501042304604', '7501042304611',
       '7501042305762', '7501042306561', '7501058712745', '7501058712813',
       '7501058713780', '7501058714596', '7501058714909', '7501058714954',
       '7501058715012', '7501058715029', '7501058715036', '7501058715098',
       '7501058715364', '7501058715432', '7501058715531', '7501058715883',
       '7501058715890', '7501058716040', '7501058716064', '7501058716071',
       '7501058716088', '7501058716095', '7501058716422', '7501058716439',
       '7501058716446', '7501058716453', '7501058716477', '7501058716767',
       '7501058716798', '7501058716804', '7501058717009', '7501058717016',
       '7501058717023', '7501058717030', '7501058717115', '7501058717122',
       '7501058717252', '7501058717276', '7501058751188', '7501058751195',
       '7501058751461', '7501058752772', '7501058753199', '7501058753205',
       '7501058753212', '7501058753304', '7501058753328', '7501058753441',
       '7501058753458', '7501058755834', '7501058755841', '7501058757449',
       '7501058757463', '7501058757548', '7501058757555', '7501058757630',
       '7501058757647', '7501058757722', '7501058757753', '7501058757791',
       '7501058757807', '7501058757838', '7501058757883BP1',
       '7501058757890', '7501058757906', '7501058780195', '7501058780201',
       '7501058780409BP1', '7501058782694BP1', '7501058783332BP2',
       '7501058783349BP1', '7501058784346', '7501058784353',
       '7501058784575', '7501058784889', '7501058785688', '7501058785695',
       '7501058786043', '7501058786050', '7501058786357',
       '7501058786548BP1', '7501058787637', '7501058787965',
       '7501058788498', '7501058788931', '7501058789365',
       '7501058790415BP1', '7501058790422BP1', '7501058790705BP2',
       '7501058790712BP2', '7501058790965', '7501058791443',
       '7501058791474BP1', '7501058791658BP1', '7501058792303',
       '7501058792778BP1', '7501058792778BP2', '7501058792808BP1',
       '7501058792808BP2', '7501058793898', '7501058794949BP1',
       '7501058794949BP2', '7501058794956BP1', '7501058794956BP2',
       '7501058794963BP1', '7501058794963BP2', '7501058794970BP1',
       '7501058794970BP2', '7501058795892', '7501058795908',
       '7501058796578BP1', '7501058796578BP2', '7501058796585',
       '7501058796837', '7501058796844', '7501058796851', '7501058796868',
       '7501058796950BP1', '7501058797865BP2', '7501058799876',
       '7501071900105', '7501071900112', '7501071900129', '7501071900136',
       '7501071900143', '7501071900174', '7501071900228', '7501071900242',
       '7501071901393', '7501071901591', '7501071901867', '7501071901874',
       '7501071902055', '7501071902086', '7501071902093', '7501071902109',
       '7501071902246', '7501071902277', '7501071902314', '7501071902369',
       '7501071902376', '7501071902475BP1', '7501071902475BP2',
       '7501071902482', '7501071902819', '7501071902918BP2',
       '7501071902932', '7501071902949', '7501071902956', '7501071903038',
       '7501071903304', '7501071903311', '7501071903335', '7501071903342',
       '7501071903359', '7501071903366', '7501071903427', '7501071903465',
       '7501071903854', '7501071903861', '7501071903878', '7501071903885',
       '7501071904103', '7501071904110', '7501071904349', '7501071904424',
       '7501071904431', '7501071904448', '7501071905285', '7501071905292',
       '7501071905339', '7501071905346', '7501071905537', '7501071905551',
       '7501071905759', '7501071905766', '7501071906701', '7501071906718',
       '7501071906725', '7501071906800', '7501071906879BP1',
       '7501071906879BP2', '7501071907074', '7501071907197',
       '7501071907227BP1', '7501071907227BP2', '7501071907401',
       '7501071907425', '7501071907517', '7501071907654', '7501071907661',
       '7501071907692', '7501071907715', '7501071907722', '7501071907784',
       '7501071908385', '7501080900134', '7501080900141', '7501080900158',
       '7501080900165', '7501080900585', '7501080952386', '7501080952973',
       '7501080952980', '7501080952997', '7501080954786', '7501080954793',
       '7501080955028', '7501080955103', '7501080955486', '7501080955530',
       '7501080955554', '7501080955561BP1', '7501080955721BP2',
       '7501080955721BP3', '7501080955776BP2', '7501080955783BP2',
       '7501080955899BP1', '7501126570598', '7501205412122',
       '7501268200001', '7501268200025', '7501268200049', '7501268200070',
       '7501268200261', '7501268200322', '7501268200339', '7501268200506',
       '7501268200513', '7501681100018', '7501681100049', '7501681100087',
       '7501681100209', '7501681100216', '7501681100223', '7501681100247',
       '7501681100254', '7501681100292', '7501681100384', '7501681100414',
       '7501681100421', '7501681100438', '7501681100445', '7501681100469',
       '7501681100513', '7501681100643BP1', '7501681100643BP2',
       '7501681100650BP1', '7501681100650BP2', '7501681100674',
       '7501681100766', '7501681100773', '7501681100810', '7501681101084',
       '7501681101299', '7502217411776', '7502240947471BP4',
       '7502240947488BP4', '7502267450312', '7502271940007',
       '7502275145897', '7502283280818', '7503000256017', '7503002319529',
       '7503002319536', '7503002319543', '7503018718675', '7503025939353',
       '7503031116083', '7503544040257', '7702137007145', '7702137007152',
       '7702137007169', '7702137007176', '7702137007183',
       '7702626204208BP1', '7702626213774', '7702626213781',
       '7891035040191', '7891035040276', '8410907050053', '8411660040503',
       '8411660210012', '8411660210029', '8411660210036',
       '7501681101305BP1', '7501058789778BP1', '7501025412142', nan,
       '7502240948188BP1'], dtype=object)

In [82]:
df_product['ITEM_DESCRIPTION'].unique()

array(['CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 0000075000592',
       'CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 0000075000608',
       'CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 0000075000615',
       'CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 0000075000622',
       'CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 0000075000639',
       'CLORALEX FANTASIA FLORAL BOT PLAST 950ML NAL 0000075000646',
       'CLORALEX FANTASIA FLORAL BOT PLAST 2000 ML NAL 0000075000653',
       'CLORALEX FRESCURA CITRICA  BOT PLAST 950ML NAL 0000075000677',
       'CLORALEX FRESCURA CITRICA BOT PLAST 2000ML NAL 0000075000684',
       'PATITO BOTELLA 245 ML. 0000075010539',
       'LYSOL SANITIZANTE DE ROPA CRISP LINEN BOT 1.2 LT 0019200958714',
       '9TIDE LIPIADOR DE ROPA QUITAMANCHAS PLUMON 10 ML IMP 0037000018704',
       '9TIDE ADIVITO QUITAMANCHAS 220 GR 0037000213215',
       '9TIDE BOOST VIVID WHITE + BRIGHT BOL 18CAP = 400GR IMP 0037000830870',
       'TIDE MULTI PURPOSE OXI STAIN REMOVER BOT 1.72KG 0037000889281',
       '9VALUE CLORO SPECIAL BOT PLAST 3780ML 0041380309109',
       'SPECIAL VALUE CLORO BLANQUEADOR REGULAR BOT  3.79 LT 0041380309116',
       '9ARCTIC WHITE FRESCO BOT.PLAS 3.79ML MP 0041596020959',
       'CLORALEX COLOR VINEGAR POWER BOTE 1.8LT 0043152007114',
       '9CLOROX REGULAR BOT.PLA 946ML IMP 0044600002033',
       'CLOROX ULTIMATE  CARE BOTELLA 887 ML IMP 0044600016924',
       'CLOROX 2 STAIN FIGTHER REMOVER PEN FOR COLORS GEL 56GR 0044600305974',
       'CLOROX 2 QUITAMANCHAS ROPA COLOR C/ROCIADOR 887ML 0044600306414',
       'CLOROX 2 DARKS&DENIM STAIN REMOVER BOT 975ML 0044600312804',
       'CLOROX CONTROL BLEACH CRYSTALS REGULAR SCENT BOT 680GR 0044600313429',
       'CLOROX CONTROL BLEACH CRYSTALS FRESH MEADOW SCENT BOT 680GR 0044600313436',
       'CLOROX CONTROL BLEACH 12 PODS CLORO EN POLVO BOT 252GR 0044600313719',
       'SHOUT TRIPLE ACCION LAUNDRY STAIN REMOVER BOT C/ATOM 650 ML 0046500022517',
       'SHOUT ADVANCED LAUNDRY STAIN REMOVER ULTRA CONC GEL BOT246GR 0046500022692',
       'SHOUT TRIPLE ACCION LAUNDRY/STAIN REMOVER BOTELLA 1.77 LT 0046500022746',
       'SHOUT ADVANCED LAUNDRY STAIN REMOVER GEL BOT C/ATOM 414ML 0046500222979',
       'SHOUT LAUNDRY STAIN REMOVER BOTELLA C/ATOMIZADOR 650 ML 0046500729355',
       'POWER HOUSE BLANQUEADOR REGULAR BOT.PLAS 22OZ=651ML IMP 0048155906310',
       '9WHITE MAGIC BOT.PLAS 3970ML IMP 0079893431208',
       'CLORALEX REGULAR BOT 950 ML NAL 0123456808218',
       'MARIPOSA DESMANCHADOR Y ABRILL.ROPA BLAN/COLOR BOTE150GR NAL 0602925200017',
       'MARIPOSA POLVO 500GR 0602925200031',
       'DON CLORINO CLORO POLVO CONCENTRADO CAJA 8SOB 7GR C/U=56GR 0612464080148',
       'BOGAMAR CLORO BOT PLAS 980ML NAL 0616533000525',
       'BOGAMAR BOTELLA 3750 ML NAL 0616533000532',
       'LA S TOTALLY AWESOME BLANQ. REGULAR GALON 3780 ML 0722429128034',
       'SEVENTH GENERATION CLORO LIBRE DE BLANQUEADOR GALON 1.89LT 0732913227013',
       'LA ANITA BLANQUEADOR REGULAR 3.785ML GALON NAL 0737128047005',
       'LA ANITA BOT.PLAST. 1000ML NAL 0737128127004',
       'LA ANITA BOT.PLAST. 500ML NAL. 0737128247009',
       'CLARASOL BLANQUEADOR REGULAR BOT PLAST 1LT NAL 0741120000005',
       'CLARASOL BLANQUEADOR REGULAR BOT PLAST 500ML NAL 0741120000012',
       'CLARASOL REGULAR SIN AROMA GARRAFON 3.785 LT 0741120000029',
       'CLARASOL BLANQUEADOR REGULAR BOT PLAS 1850 ML 0741120000036',
       'CLARASOL GEL PODER CONCENTRADO BOT PLAS 1L 0741120000746',
       'CLARASOL BOT.PLAST. 1000ML NAL 0741120010011',
       'OXI CLEAN MAX FORCE REMOVEDOR/MANCHAS BOT. PLAST 266.16ML 0757037000489',
       'OXI CLEAN MAX FORCE REMOVEDOR DE MANCHAS BOT. PLAST 354 ML 0757037512449',
       'OXI CLEAN MAX FORCE GEL STICK REMOVEDOR D/MANCHAS 1PZA 175GR 0757037513552',
       '9OXI CLEAN ELIMINADOR D/MANCHAS BOTE PLAST. 1580 GR IMP. 0757037514016BP1',
       'OXI CLEAN REMOVEDOR DE MANCHAS BOTE 636ML 0757037516935',
       'OXI CLEAN LIQ.BOT. 635 ML 0757037517123',
       'OXI CLEAN REMOVEDOR DE MANCHAS BOT. 453 GR 0757037517499',
       '9OXICLEAN ELIMINADOR DE MANCHAS BOTE 750 GR IMP 0757037517611',
       'SANYTOL DESINFECTANTE DE ROPA BOT 500 ML 3045200760009',
       'SANYTOL DESINFECTANTE DE ROPA BOT 1 LT 3045206360609',
       'SANYTOL QUITAMANCHAS DESINFECTANTE POLVO BOT 450GR 3045206382007',
       'DR BECKMANN EL MAGO QUITAMANCHAS 4 LIQUIDO BOT 50ML IMP 4008455394015',
       'DR BECKMANN EL MAGO QUITAMANCHAS 2 LIQUIDO BOT 50ML IMP 4008455394114',
       'DR BECKMANN EL MAGO QUITAMANCHAS 8 LIQUIDO BOT 50ML IMP 4008455394213',
       'DR BECKMANN EL MAGO QUITAMANCHAS3 P.TINT/CRAY/ROTUL BOT 50ML 4008455394411',
       'DR BECKMANN EL MAGO QUITAMANCHAS 5 LIQUIDO BOT 50ML IMP 4008455394510',
       'DR BECKMANN EL MAGO QUITAMANCHAS 7 LIQUIDO BOT 50ML IMP 4008455394619',
       'DR BECKMANN EL MAGO QUITAMANCHAS 6 LIQUIDO BOT 50ML IMP 4008455423517',
       'DR BECKMANN EL MAGO QUITAMANCHAS 4 LIQUIDO BOT 50ML IMP 4008455423616',
       'DR BECKMANN QUITAMANCHAS PRELAVADO C/CEP APLIC LIQ BOT 250ML 4008455423715',
       'DR BECKMANN BLANQ INTENS SUPER BLANC PVO 6BSAS 40GRC/U=240GR 4008455425412',
       'DR BECKMANN POLVO QUITA DESTINIDO CJ C/2 BOL 75GC/U=150GRS 4008455427614',
       'DR BECKMANN LAPIZ MAGICO QUITAMANCHAS 9ML 4008455438016',
       'DR BECKMANN BLANQUEADOR SIN CLORO BOL 80GR 4008455457512',
       'DR BECKMANN QUITAMANCHASINTENSO ROPABLANCAYCOLOR SACHET100GR 4008455457710',
       'DR BECKMANN EL MAGO QUITAMANCHAS OXIDO/DESOD BOTC/ATOM 250ML 4008455458618',
       'DR BECKMANN ORIGINAL QUITAMANCHAS PRELAVADO BOT C/ATOM 250ML 4008455458717',
       'DR BECKMAN SUPER BLANCO TOALLITAS ACTIVAS S/CLORO CAJA 15PZ 4008455459417',
       'DR BECKMANN BLANQUEADOR POLVO CJ C/2BOLSAS 75GRC/U=150GR IMP 4008455460215',
       'DR BECKMANN JABON MAGICO QUITAMANCHAS BARRA 100 GR 4008455476711',
       'DR BECKMANN QUITAMANCHAS DESODORANTE Y SUDOR BOT 500 ML 4008455524917',
       'DR BECKMANN QUITAMANCHAS INTENSO ROPABLANCAYCOLOR SOBRE 80GR 4008455567013',
       'TOTAL CUELLOS PUNOS Y MANCHITAS ULTRA FUERTE LATA 340GR NAL 7501021160689',
       'H24 CUELLOS PUNOS Y MANCHITAS BOT/ATOM 700ML NAL 7501021160719',
       'CUELLOS PU¤OS Y MANCHITAS BOT/REP 700 ML  NAL. 7501021160726',
       'CLORALEX FLORES DE BACH BOT PLAS 950 ML 7501025400323',
       'CLORALEX FLORES DE BACH BOT PLAS 2 LT 7501025400330',
       'CLORALEX FLORES DE BACH BOT PLAS 3.75 LT 7501025400347',
       'CLORALEX GERANIO Y ALOE BOT PLAS 950 ML 7501025400354',
       'CLORALEX GERANIO Y ALOE BOT PLAS 2 LT 7501025400361',
       'CLORALEX GERANIO Y ALOE BOT PLAS 3.75 LT 7501025400378',
       'CLORALEX MENTA Y EUCALIPTO BOT PLAS 950 ML 7501025400385',
       'CLORALEX MENTA Y EUCALIPTO BOT PLAS 2 LT 7501025400392',
       'CLORALEX MENTA Y EUCALIPTO BOT PLAS 3.75 LT 7501025400408',
       'CLORALEX SUAVE AROMA BLANQUEADOR BOT 950ML 7501025400415',
       'CLORALEX SUAVE AROMA BLANQUEADOR BOT 2LT 7501025400422',
       'CLORALEX SUAVE AROMA BLANQUEADOR BOT 3.75LT 7501025400439',
       'CLORALEX CLORO GERMICIDA REGULAR 950 ML 7501025400767',
       'CLORALEX EL RENDIDOR BLANQUEADOR DESINF ELIM COVID BOT 950ML 7501025400781',
       'RADIANTE QUITA MANCHAS P/ROPA BOT 1000ML NAL 7501025400903',
       'CLORALEX COLOR QUITAMANCHAS PARA ROPA BOT 500 ML NAL 7501025400927',
       'CLORALEX COLOR QUITAMANCHAS P/ROPA BOT 950 ML NAL 7501025400941',
       'CLORALEX COLOR QUITAMANCHAS ROPA BOT 1800 ML NAL 7501025400958',
       'CLORALEX COLOR QUITA MANCHAS ROPA BOT C/ATOM 650 ML 7501025400965',
       'CLORALEX ESFERAS ROPA COLOR BOTE 500GR NAL 7501025400989',
       'CLORALEX ESFERAS ROPA DE COLOR QUITAMANCHAS BOTE 1000 GR 7501025400996',
       'CLORALEX EXTRA SENSACION FRUTALES BOT PLAST 950ML 7501025401023',
       'CLORALEX AROMA SENSACION FRUTAL BOT PLAST 3750ML 7501025401047',
       'CLORALEX BAMBINO BOT PLAST 950ML NAL 7501025401061',
       'CLORALEX BAMBINO BOT PLAST 2000ML NAL 7501025401078',
       'CLORALEX BLANQUEDOR ESENCIAS DE MARSELLA BOTPLAS 950ML NAL 7501025401115',
       'CLORALEX ESENCIAS DE MARSELLA BOT PLAS 2000 ML NAL 7501025401122',
       'CLORALUZ BOT.PLAST. 900ML NAL. 7501025401252',
       'CLORALEX EL RENDIDOR BOTELLA 10000 ML NAL 7501025401306',
       'CLORALEX CLORO EN GEL BOT 3.75L 7501025401313',
       'CLORALEX BRISA FRESCA BOT PLAST 950ML NAL 7501025401511',
       'CLORALEX EXTRA BRISA FRESCA BOT PLAST 2LTS NAL 7501025401528',
       'CLORALEX EL RENDIDOR BOT 1.17LT 7501025401535',
       'CLORALEX SUAVE AROMA BLANQUEADOR BOT 1.17L 7501025401566',
       'CLORALEX COLOR PODER VINAGRE QUITAMANCHAS BOLSA 450 ML 7501025401573',
       'CLORALEX COLOR QUITAMANCHAS BOLSA 450 ML 7501025401580',
       'CLORALEX COLOR SIN CLORO BOT 2.8 LT 7501025401597BP1',
       'CLORALEX EXTRA BRISA FRESCA 375OML NAL 7501025401641',
       'CLORALEX ULTRAGEL CITRICO BOTELLA 950ML 7501025401795',
       'CLORALEX ULTRAGEL CITRICO BOTELLA 600ML 7501025401801',
       'CLORALEX  PODER OXIGENO ULTRAGEL QUITAMANCHAS BOLSA 450 ML 7501025401832',
       'CLORALEX PODER OXIGENO ULTRAGEL QUITAMANCHAS BOLSA 750 ML 7501025401849',
       'CLORALEX PODER  OXIGENO ULTRAGEL QUITAMANCHAS BOT 950 ML 7501025401856',
       'CLORALEX PODER OXIGENO  ULTRAGEL  QUITAMANCHAS BOT 1.5 LT 7501025401863',
       'CLORALEX  PODER VINAGRE ULTRAGEL QUITAMANCHAS BOLSA 450 ML 7501025401887',
       'CLORALEX PODER VINAGRE ULTRAGEL QUITAMANCHAS BOLSA 750 ML 7501025401894',
       'CLORALEX PODER  VINAGRE ULTRAGEL QUITAMANCHAS BOT 950 ML 7501025401900',
       'CLORALEX PODER VINAGRE ULTRAGEL  QUITAMANCHAS BOT 1.5 LT 7501025401917',
       'CLORALEX GEL BLANQUEADOR BP 700ML 7501025401931',
       'CLORALEX GEL NO SALPICA DESINFECTANTE BP 1.65LT 7501025401948',
       'BLANCATEL CONCENTRADO BOT PLAST 3750ML NAL 7501025401993',
       'BLANCATEL BOT.PLAST. 930 ML. NAL. 7501025402037',
       'BLANCATEL CONCENTRADO BOT PLAST 3750ML NAL 7501025402051',
       'BLANCATEL FRESCURA DEL CAMPO BOT PLAST 3750ML NAL 7501025402082',
       'BLANCATEL BLANQUEADOR FAMILIAR JAZMIN GFA 3.75 LT 7501025402211',
       'BLANCATEL FLORAL BOT PLAST 3750ML NAL 7501025402235',
       'BLANCATEL LAVANDA LIQ BOT PLAST 3750ML NAL 7501025402242',
       'BLANCATEL BLANQUEADOR BOTELLA 1.8LT 7501025402259',
       'BLANCATEL N. BLANQUEADOR BOTELLA 3.75LT 7501025402303',
       'CLORALEX EL RENDIDOR BLANQUEADOR ROPA CONCENT GARRAFON 7 LT 7501025402440',
       'BLANCATEL NAVIDENO BOT PLAST 3.750LT NAL 7501025402990',
       'CLORALEX EDICION RETRO BOTELLA 2000 ML 7501025403423',
       'CLORALEX CLORO EN GEL BOT 500ML 7501025405076',
       'CLORALEX ULTRAGEL CLORO GEL CONCENTRADO BOT 600 ML 7501025405090',
       'CLORALEX CLORO EN GEL BP 2000ML 7501025405106',
       'CLORALEX CLORO EN GEL BOT 250ML 7501025405120',
       'CLORALEX CLORO EN GEL BOT 950ML 7501025405151',
       'CLORALEX AROMAX FLORAL CLORO GEL CON DETERGENTE BOT 600ML 7501025405205',
       'CLORALEX ULTRAGEL CLORO EN GEL CONCENTRADO 950ML 7501025405212',
       'CLORALEX AROMAX CLORO GEL C/DETERGENTE CITRICO BOTE 950ML 7501025405229',
       'CLORALEX AROMAX CLORO GEL C/DETERGENTE FLORAL BOTE 950ML 7501025405236',
       'CLORALEX DETERMAX GEL BOT PLAS 950 ML 7501025405274',
       'CLORALEX MAXGEL BOT 600ML+PINOL PINO MULTIU BOT 1L 7501025405298BP2',
       'CLORALEX EL RENDIDOR 60 ANIVERSARIO 950+220 ML=1170 ML NAL 7501025405311',
       'CLORALEX EL RENDIDOR ELIMINA 99.9 DE VIRUS Y BACTERIAS BOT 1 7501025405816',
       'CLORALEX GEL ROPA BLANCA BP 950 ML 7501025405885',
       'CLORALEX AROMA CLORO LIQUIDO LAVANDA BP 2L 7501025406561',
       'CLORALEX AROMA CLORO LIQUIDO LAVANDA BP 3.75L 7501025406578',
       'CLORALEX AROMAS BLAQUEADOR LIQUIDO FLORAL GAR 10LT 7501025408404',
       'CLORALEX EL RENDIDOR BOT.PLAST. 700ML NAL. 7501025408947',
       'CLORALEX EL RENDIDOR BLANQ DESINF DEODORIZ CONCEN BP 1.65LT 7501025409104',
       'CLORALEX MASCOTAS LIMP DESINFECT C/CLORO BP C/G750ML=3.750LT 7501025409470',
       'CLORALEX COLOR LIQUIDO PRELAVADOR BOTELLA 1.8 LT 7501025410834',
       'CLORALEX MASCOTAS LIM C/CLORO+DETERGENTE CITRICO BP 1.65L 7501025411893',
       'CLORALEX AREA MASCOTAS BOTELLA 1800ML + 200ML = 2 LT 7501025411978',
       'CLORALEX MASCOTAS BOT PLAST 950ML NAL 7501025411992',
       'CLORALEX MASCOTAS BOT PLAST 3750ML NAL 7501025412005',
       'CLORALEX MASCOTAS BOT PLAST 5000ML NAL 7501025412012',
       'CLORALEX AROMA CLORO LIQUIDO FLORAL BP 950ML 7501025412104',
       'CLORALEX AROMA CLORO LIQUIDO FLORAL BP 3.75L 7501025412135',
       'CLORALEX EL RENDIDOR CLORO LIQ DESINFECT C/G500ML BOT=3.75L 7501025412357',
       'CLORALEX COLOR PODER VINAGRE BOT 950 ML NAL 7501025412401',
       'CLORALEX COLOR PODER VINAGRE BOT 1800 ML NAL 7501025412418',
       'CLORALEX COLOR PODER VINAGRE GARRAFON 5100 ML NAL 7501025412463',
       'CLORALEX COLOR QUITAMANCHAS BOT 950 ML 7501025412784',
       'CLORALEX BLANQUEADOR FLORES MEXICANAS BOT PLAS 2 LT 7501025418106',
       'CLORALEX ELRENDIDORLIQBP950MLPVPESP+PINOLELORIGFLORALBP828ML 7501025441319BP2',
       'CLORALEX ELRENDIDORLIQBP950ML+PINOLELORIGCITRICOBP828MPVPESP 7501025441326BP2',
       'MMBLANQUEADORCONC BP950ML+CLORALEX BAÑOSANTIHONGOS ATOM650ML 7501025441357BP1',
       'CLORALEX BLANQUEADOR REG BP950ML+PINOL EL ORIGINAL LIMPBP1LT 7501025441463BP2',
       'CLORALEX EL RENDIDOR LIQ BP950ML+MM EL RENDIDOR GEL BP950ML 7501025441487BP1',
       'CLORALEX EL RENDIDOR GEL BP950ML+MM EL RENDIDOR LIQ BP950ML 7501025441487BP2',
       'CLORALEX EL RENDIDOR BOT 1900+100ML= 2LT 7501025450212',
       'CLORALEX EL RENDIDOR CONCENTRADO BOT 1800ML C/G 200ML = 2 LT 7501025450274',
       'CLORALEX REGULAR LIQ BOT PLAS 950ML C/MM ROPA COLOR 950ML 7501025450618BP1',
       'CLORALEX ROPA COLOR BOT PLAS 950ML C/MM REGULAR LIQ 950ML 7501025450618BP2',
       'CLORALEX EL RENDIDOR BOT PLAST 3750ML+300ML GRATIS 4050ML 7501025450632',
       'CLORALEX MASCOTAS LA PAREJA PERFECTA 2BOT 950ML C\\U 7501025450984',
       'CLORALEX RENDIDOR BOT 950ML+MM MASCOTAS BOT 950ML 7501025450984BP1',
       'CLORALEX MASCOTAS BOT 950ML+MM RENDIDOR BOT 950ML 7501025450984BP2',
       'CLORALEX MASCOTAS INTERIOR BOT C/ATOM 650ML NAL 7501025454012',
       'CLORALEX MASCOTAS INTERIOR BOT PLAST 950ML NAL 7501025454029',
       'CLORALEX AROMA MUJER CAMPANA UNIDAS CONTIGO 3.750 LT 7501025459208',
       'CARISMA CLORO BOTELLA 1LT 7501026005800',
       'CLORO PURO SOL BOT PLAS 1000 ML LA CORONA 7501026030109',
       'EL TIMON BLANQUEADOR AZUL PARA ROPA 50SOBRES 10GR C/U 7501041505309',
       'MYRSEL CLORO INCOLORO E INHOLORO GARRAFON 20LTS NAL 7501041508652',
       'PATITO CLORO PATITO BOT.PLAST.960 ML NAL. 7501042300033',
       'CLORO PATITO BOT PLAS 3750 ML NAL. 7501042300057',
       'CLORTEX BLANQUEADOR BOT 1890ML NAL 7501042301733',
       'CLORTEX BLANQUEADOR CONCENTRADO SIN AROMA GARRAFON 3.75 LT 7501042301740',
       'CLORTEX BOT PLAS 950 ML NAL. 7501042301757',
       'CLORTEX AROMA FLORAL BOT PLAS 3750ML NAL 7501042301764',
       'CLORTEX AROMA LAVANDA BOT PLAS 3750ML NAL 7501042301771',
       'CLORTEX AROMA MANZANA VERDE BOT PLAS 3750ML NAL 7501042301788',
       'LA JAPONESA BLANQUEADOR BOT PLAST 150GR NAL 7501042302556',
       'CLORO 10 BOTELLA  950 ML 7501042304604',
       'CLORO 10 BOTELLA 3900 ML NAL. 7501042304611',
       'CLORTEX BLANQUEADOR CONCENTRADO BOTELLA PLA 2.84 LT NAL 7501042305762',
       'CLORTEX BLANQUEADOR MASCOTAS BOTELLA 3.75 LT 7501042306561',
       'VANISH SUPER BARRA ROSA 20%MAS=81GR 7501058712745',
       'VANISH OXI ACTION QUITAMANCHAS P/ROPA BOTE 240G 7501058712813',
       'VANISH OXI ACTION ROSA QUITA MANCHAS PARA LA ROPA BOT 150GR 7501058713780',
       'VANISH SUPER BARRA QUITA MANCHAS 68GR 7501058714596',
       'VANISH OXI ACTION ROSA QUITA MANCHAS PACK 2 BOT 450GR C/U 7501058714909',
       'VANISH CRISTAL WHITE SUPER BARRA 20%MAS=81G 7501058714954',
       'VANISH OXI ACTION CRISTAL WHITE BOT 150GR 7501058715012',
       'VANISH MULTIUSOS REMOVEDOR S/CLORO DE MANCHAS DOYPACK 500ML 7501058715029',
       'VANISH WHITE QUITAMANCHAS Y BLANQ.S/CLORO DOYPACK 500ML 7501058715036',
       'VANISH OXI ACTION QUITA MANCHAS BOT 240GR 7501058715098',
       'VANISH MULTIUSOS REMOV S/CLORO MANCHAS BOT 420ML 7501058715364',
       'VANISH ROSA LIQ. DOYPACK 100ML 7501058715432',
       'VANISH COLOR QUITAMANCHAS GEL DOYPACK 150ML 7501058715531',
       'VANISH OXI ACTION GOLD QUITAMANCHAS BOLSA 1.8KG 7501058715883',
       'VANISH OXI ACTION CRISTAL WHITE BOLSA 1.8KG 7501058715890',
       'VANISH SUPER BARRA GOLD QUITAMA C/ENZIMA 2PZAS 68GRC/U=136GR 7501058716040',
       'VANISH OXI ACTION ROSA QUITA/MANCHAS P/ROPA BOT 810GR 7501058716064',
       'VANISH OXI ACTION CRISTAL WHITE QUITAMANCHAS P/ROPA BOT810GR 7501058716071',
       'VANISH ROSA MULTIUSO REMOVEDOR SIN CLORO DE MANCHAS BOT3.6LT 7501058716088',
       'VANISH WHITE LIQUIDO QUITAMANCHAS+BLANQ S/CLORO BOT 3.6LT 7501058716095',
       'VANISH OXI ACTION GOLD QUITAMANCHA AHORRO DEL 30% BOT 400GR 7501058716422',
       'VANISH OXI ACTION GOLD QUITAMANCHAS AHORRO DEL 25% BOT 500GR 7501058716439',
       'VANISH OXI ACTION CRISTAL WHITE AHORRO DEL 25% BOT 500GR 7501058716446',
       'VANISH MULTIUSOS ROSA REMOV/MAN SUPER AHORRO DEL30% BOT1.5LT 7501058716453',
       'VANISH MULTIUSOS REMOVEDOR D/MANCHAS 25%GRATIS DOYPACK 650ML 7501058716477',
       'VANISH ROSA QUITAMANCHAS GEL BOT 3.8 LT PROM ESP 7501058716767',
       'VANISH CRYSTAL WHITE QUITAMANCHAS GEL BOT 3.8 LT PROM ESP 7501058716798',
       'VANISH OXY ACTION ROSA PRELAVADOR PARA ROPA DOYPACK 500ML 7501058716804',
       'VANISH OXI ACTION ROSA QUITAMANCHAS BOT 120GR 7501058717009',
       'VANISH OXI ACTION CRISTAL WHITE BOT 120 GR 7501058717016',
       'VANISH ROSA QUITAMANCHAS GEL MULTIUSOS POUCH 450 ML 7501058717023',
       'VANISH CRYSTAL WHITE QUITAMANCHAS GEL POUCH 450 ML 7501058717030',
       'LYSOL CRISP LINEN SANITIZANTE DE ROPA BOT 1 LT 7501058717115',
       'LYSOL SANITIZANTE DE ROPA CRISP LINEN BOT 2 LT 7501058717122',
       'LYSOL SANITIZANTE DE ROPA CRISP LINEN SCENT POUCH 500 ML 7501058717252',
       'LYSOL SANITIZANTE DE ROPA SPORT BOTELLA 1.21 LT 7501058717276',
       'VANISH WHITE REMOVEDOR DE MANCHAS BOT   1700 ML 7501058751188',
       'VANISH WHITE BOTELLA 900 ML 7501058751195',
       'VANISH WHITE REMOVERD D/MANCHAS Y BLANQ.S/CLORO LIQ.BOT4000M 7501058751461',
       'VANISH PINK DESMANCHADOR LIQ. BOTELLA 450 ML NAL 7501058752772',
       'VANISH EXTRA-HIGIENE BOLSA 600 ML DOYPACK 7501058753199',
       'VANISH EXTRA-HIGIENE BOTELLA PLASTICO 900 ML 7501058753205',
       'VANISH EXTRA-HIGIENE PODER 02 BOTE 420GR 7501058753212',
       'VANISH EXTRA-HIGIENE PODER 02 BOTE 870GR 7501058753304',
       'VANISH ROSA ROPA COLOR LIQ.S/CLORO ROPA FLEXIPACK 250ML NAL 7501058753328',
       'VANISH PODER O2 DOYPACK 120 GR 7501058753441',
       'VANISH PODER O2 CRYSTAL WHITE DOYPACK 120 GR 7501058753458',
       'HARPIC ULTRA CLORO GEL CITRUS BOT 650ML 7501058755834',
       'HARPIC ULTRA CLORO GEL FRESH BOT 650ML 7501058755841',
       'VANISH PODER02 CRYSTAL WHITE S/C PVO. ROPA TARRO PLAST.900GR 7501058757449',
       'VANISH WHITE LIQ REMOVEDOR DE MANCHAS BOT 435ML NAL 7501058757463',
       'VANISH ROSA COLOR LIQ. DOYPACK 650ML NAL 7501058757548',
       'VANISH WHITE LIQUIDO DOY PACK 600ML NAL 7501058757555',
       'VANISH PODER O2 PRE-LAVADOR BOT.ATOM. 650 ML NAL 7501058757630',
       'VANISH PODER O2 PRE LAVADOR BOT.REP. 650 ML 7501058757647',
       '9VANISH PODER O2 BOTE  500 GR IMP 7501058757722',
       'VANISH PODER O2 REMOVEDOR DE MANCHAS BOT 1000 GR NAL 7501058757753',
       'VANISH BOT. 4000 ML. 7501058757791',
       'VANISH MAX REMOVEDOR DE MANCHAS ROPA BOLSA 445ML NAL 7501058757807',
       'VANISH PODER O2 GEL BOTELLA   500 ML 7501058757838',
       'VANISH LIQUIDO SIN AROMA GARRAFON 6 LTS NAL. 7501058757883BP1',
       'VANISH PODER O2 CRYSTAL WHITE BOTE 450  GR 7501058757890',

In [84]:
df_product['CATEGORY'].unique()

array([1], dtype=int64)

In [86]:
df_product['FORMAT'].unique()

array(['LIQUIDO', 'POLVO', 'GEL', 'TOALLAS', 'BARRA'], dtype=object)

In [88]:
df_product['ATTR1'].unique()

array(['CLORO', 'SANITIZANTE', 'SAFE BLEACH', 'PRELAVADOR', nan],
      dtype=object)

In [90]:
df_product['ATTR2'].unique()

array(['CLORO', 'SANITIZANTE', 'FABRIC TREATMENT'], dtype=object)

In [92]:
df_product['ATTR3'].unique()

array(['NO DEFINIDO', 'OTR. TIPOS', 'SANITIZANTE', 'PRE LAVADOR',
       'COLOR PODER VINAGRE', 'QUITAMANCHAS', 'ROPA COLOR', nan,
       'MULTIUSOS', 'BLANCO', 'GERMICIDA', 'BAMBINO', 'ROPA BEBE',
       'MASCOTAS', 'ROSA', 'ROPA BLANCA'], dtype=object)

In [94]:
df_product.isnull().sum()

MANUFACTURER        0
BRAND               0
ITEM                2
ITEM_DESCRIPTION    0
CATEGORY            0
FORMAT              0
ATTR1               6
ATTR2               0
ATTR3               6
dtype: int64

In [96]:
df_product['ITEM'] = df_product['ITEM'].fillna('Desconocido')
df_product['ATTR1'] = df_product['ATTR1'].fillna('Desconocido')
df_product['ATTR3'] = df_product['ATTR3'].fillna('Desconocido')
df_product.isnull().sum()

MANUFACTURER        0
BRAND               0
ITEM                0
ITEM_DESCRIPTION    0
CATEGORY            0
FORMAT              0
ATTR1               0
ATTR2               0
ATTR3               0
dtype: int64

In [98]:
df_product.dtypes

MANUFACTURER        object
BRAND               object
ITEM                object
ITEM_DESCRIPTION    object
CATEGORY             int64
FORMAT              object
ATTR1               object
ATTR2               object
ATTR3               object
dtype: object

In [100]:
df_product.duplicated().sum()

0

In [102]:
df_product = df_product.drop_duplicates()

In [104]:
df_product = df_product.sort_values('BRAND', ascending=True)
df_product

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
17,ARTIC WHITE,ARTIC WHITE,0041596020959,9ARCTIC WHITE FRESCO BOT.PLAS 3.79ML MP 004159...,1,LIQUIDO,CLORO,CLORO,OTR. TIPOS
453,JABONERA LA ESPUMA,BANDERA,7501681100414,BANDERA CLORHADA BLANQUEADOR AROMA LIMON BOT P...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
463,JABONERA LA ESPUMA,BANDERA,7501681100674,BCLORHADA CLORO+DETERGENTE MASCOTAS BOTELLA 3....,1,LIQUIDO,CLORO,CLORO,MASCOTAS
461,JABONERA LA ESPUMA,BANDERA,7501681100650BP1,B'CLORHADA CLORO+DET MASCOT BOT 1 L+MM BLANQ C...,1,LIQUIDO,CLORO,CLORO,MASCOTAS
460,JABONERA LA ESPUMA,BANDERA,7501681100643BP2,B'CLORHADA BLANQ CONCENT BOT 960 ML+MM CLORO G...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
...,...,...,...,...,...,...,...,...,...
284,RECKITT,VANISH PODER 02,7501058783349BP1,VANISH PODER O2 CRYSTAL WHITE BOT 900ML+MM ROS...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,BLANCO
221,RECKITT,VANISH PODER 02,7501058714954,VANISH CRISTAL WHITE SUPER BARRA 20%MAS=81G 75...,1,BARRA,SAFE BLEACH,FABRIC TREATMENT,BLANCO
271,RECKITT,VANISH PODER 02,7501058757722,9VANISH PODER O2 BOTE 500 GR IMP 7501058757722,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
258,RECKITT,VANISH PODER 02,7501058753212,VANISH EXTRA-HIGIENE PODER 02 BOTE 420GR 75010...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
33,WHITE MAGIC,WHITE MAGIC,0079893431208,9WHITE MAGIC BOT.PLAS 3970ML IMP 0079893431208,1,LIQUIDO,Desconocido,CLORO,Desconocido

**Esta revisión si presento algunos errores, los cuales ya fueron corregidos**

In [106]:
#4ta limpieza
df_segment.columns

Index(['CATEGORY', 'ATTR1', 'ATTR2', 'ATTR3', 'FORMAT', 'SEGMENT'], dtype='object')

In [108]:
df_segment['CATEGORY'].unique()

array([1], dtype=int64)

In [110]:
df_segment['ATTR1'].unique()

array(['CLORO', 'PRELAVADOR', 'SAFE BLEACH', 'SANITIZANTE'], dtype=object)

In [112]:
df_segment['ATTR2'].unique()

array(['CLORO', 'MASCOTAS', 'MULTIUSOS', 'NO DEFINIDO',
       'FABRIC TREATMENT', 'PRE LAVADOR', 'SANITIZANTE'], dtype=object)

In [114]:
df_segment['ATTR2'] = df_segment['ATTR2'].replace({'PRE LAVADOR': 'PRELAVADOR'})
df_segment['ATTR2'].unique()

array(['CLORO', 'MASCOTAS', 'MULTIUSOS', 'NO DEFINIDO',
       'FABRIC TREATMENT', 'PRELAVADOR', 'SANITIZANTE'], dtype=object)

In [116]:
df_segment['ATTR3'].unique()

array(['BAMBINO', 'GERMICIDA', 'MASCOTAS', 'MULTIUSOS', 'NO DEFINIDO',
       'OTR. TIPOS', 'ROPA BEBE', nan, 'BLANCO', 'PRE LAVADOR',
       'QUITAMANCHAS', 'ROPA COLOR', 'ROSA', 'COLOR PODER VINAGRE',
       'PODER OXIGENO', 'ROPA BLANCA', 'SANITIZANTE'], dtype=object)

In [125]:
df_segment['ATTR3'] = df_segment['ATTR3'].fillna('DESCONOCIDO')
df_segment['ATTR3'] = df_segment['ATTR3'].replace({'OTR. TIPOS': 'OTROS TIPOS'})

In [127]:
df_segment['ATTR3'].unique()

array(['BAMBINO', 'GERMICIDA', 'MASCOTAS', 'MULTIUSOS', 'NO DEFINIDO',
       'OTROS TIPOS', 'ROPA BEBE', 'DESCONOCIDO', 'BLANCO', 'PRE LAVADOR',
       'QUITAMANCHAS', 'ROPA COLOR', 'ROSA', 'COLOR PODER VINAGRE',
       'PODER OXIGENO', 'ROPA BLANCA', 'SANITIZANTE'], dtype=object)

In [129]:
df_segment['FORMAT'].unique()

array(['LIQUIDO', 'GEL', 'POLVO', 'TOALLAS', 'BARRA'], dtype=object)

In [131]:
df_segment['SEGMENT'].unique()

array(['BLEACH', 'LIQUID & GEL', 'POWDER', 'OTHERS', 'PRETREAT', 'BAR',
       'SANITIZER'], dtype=object)

In [133]:
df_segment.isnull().sum()

CATEGORY    0
ATTR1       0
ATTR2       0
ATTR3       0
FORMAT      0
SEGMENT     0
dtype: int64

In [135]:
df_product.dtypes

MANUFACTURER        object
BRAND               object
ITEM                object
ITEM_DESCRIPTION    object
CATEGORY             int64
FORMAT              object
ATTR1               object
ATTR2               object
ATTR3               object
dtype: object

In [137]:
df_segment.duplicated().sum()

0

In [143]:
df_segment = df_segment.drop_duplicates()

In [145]:
df_segment

,CATEGORY,ATTR1,ATTR2,ATTR3,FORMAT,SEGMENT
0,1,CLORO,CLORO,BAMBINO,LIQUIDO,BLEACH
1,1,CLORO,CLORO,GERMICIDA,LIQUIDO,BLEACH
2,1,CLORO,CLORO,MASCOTAS,LIQUIDO,BLEACH
3,1,CLORO,CLORO,MULTIUSOS,GEL,BLEACH
4,1,CLORO,CLORO,MULTIUSOS,LIQUIDO,BLEACH
5,1,CLORO,CLORO,NO DEFINIDO,LIQUIDO,BLEACH
6,1,CLORO,CLORO,NO DEFINIDO,POLVO,BLEACH
7,1,CLORO,CLORO,OTROS TIPOS,LIQUIDO,BLEACH
8,1,CLORO,CLORO,OTROS TIPOS,POLVO,BLEACH
9,1,CLORO,CLORO,ROPA BEBE,LIQUIDO,BLEACH
10,1,CLORO,CLORO,DESCONOCIDO,LIQUIDO,BLEACH
11,1,CLORO,MASCOTAS,MASCOTAS,LIQUIDO,BLEACH
12,1,CLORO,MULTIUSOS,MULTIUSOS,GEL,BLEACH
13,1,CLORO,NO DEFINIDO,NO DEFINIDO,LIQUIDO,BLEACH
14,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,GEL,LIQUID & GEL
15,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,POLVO,POWDER
16,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,TOALLAS,OTHERS
17,1,PRELAVADOR,FABRIC TREATMENT,OTROS TIPOS,LIQUIDO,PRETREAT
18,1,PRELAVADOR,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRETREAT
19,1,PRELAVADOR,FABRIC TREATMENT,PRE LAVADOR,POLVO,POWDER
20,1,PRELAVADOR,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,PRETREAT
21,1,PRELAVADOR,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,PRETREAT
22,1,PRELAVADOR,FABRIC TREATMENT,ROSA,GEL,LIQUID & GEL
23,1,PRELAVADOR,FABRIC TREATMENT,ROSA,LIQUIDO,PRETREAT
24,1,PRELAVADOR,FABRIC TREATMENT,ROSA,POLVO,POWDER
25,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,BARRA,BAR
26,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,GEL,LIQUID & GEL
27,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,LIQUIDO,LIQUID & GEL
28,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,POLVO,POWDER
29,1,SAFE BLEACH,FABRIC TREATMENT,COLOR PODER VINAGRE,GEL,LIQUID & GEL
30,1,SAFE BLEACH,FABRIC TREATMENT,COLOR PODER VINAGRE,LIQUIDO,LIQUID & GEL
31,1,SAFE BLEACH,FABRIC TREATMENT,OTROS TIPOS,BARRA,BAR
32,1,SAFE BLEACH,FABRIC TREATMENT,OTROS TIPOS,GEL,LIQUID & GEL
33,1,SAFE BLEACH,FABRIC TREATMENT,OTROS TIPOS,LIQUIDO,LIQUID & GEL
34,1,SAFE BLEACH,FABRIC TREATMENT,OTROS TIPOS,POLVO,POWDER
35,1,SAFE BLEACH,FABRIC TREATMENT,PODER OXIGENO,GEL,LIQUID & GEL
36,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BARRA,BAR
37,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,GEL,LIQUID & GEL
38,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRETREAT
39,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,POLVO,POWDER
40,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,GEL,LIQUID & GEL
41,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,LIQUID & GEL
42,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,POLVO,POWDER
43,1,SAFE BLEACH,FABRIC TREATMENT,ROPA BLANCA,LIQUIDO,LIQUID & GEL
44,1,SAFE BLEACH,FABRIC TREATMENT,ROPA BLANCA,POLVO,POWDER
45,1,SAFE BLEACH,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,LIQUID & GEL
46,1,SAFE BLEACH,FABRIC TREATMENT,ROPA COLOR,POLVO,POWDER
47,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,BARRA,BAR
48,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,GEL,LIQUID & GEL
49,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,LIQUIDO,LIQUID & GEL
50,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,POLVO,POWDER
51,1,SAFE BLEACH,PRELAVADOR,PRE LAVADOR,GEL,PRETREAT
52,1,SANITIZANTE,SANITIZANTE,SANITIZANTE,LIQUIDO,SANITIZER

**Presento unos ligeros datos erroneos e incompletos, sin embargo fueron corregidos**

### Unir los DataFrames relevantes

In [147]:

product_segment_merged = pd.merge(df_product, df_segment, on='CATEGORY', how='left')

product_segment_category_merged = pd.merge(product_segment_merged, df_category, left_on='CATEGORY', right_on='ID_CATEGORY', how='left')

product_segment_category_merged['DATE'] = pd.date_range(start='2024-01-01', periods=len(product_segment_category_merged), freq='D')

final = pd.merge(product_segment_category_merged,df_calendar,on='DATE',how='left')

final.head()

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY_x,FORMAT_x,ATTR1_x,ATTR2_x,ATTR3_x,ATTR1_y,...,ATTR3_y,FORMAT_y,SEGMENT,ID_CATEGORY,CATEGORY_y,DATE,WEEK,YEAR,MONTH,WEEK_NUMBER
0,ARTIC WHITE,ARTIC WHITE,0041596020959,9ARCTIC WHITE FRESCO BOT.PLAS 3.79ML MP 004159...,1,LIQUIDO,CLORO,CLORO,OTR. TIPOS,CLORO,...,BAMBINO,LIQUIDO,BLEACH,1,FABRIC TREATMENT AND SANIT,2024-01-01,52-23,2023.0,1.0,52.0
1,ARTIC WHITE,ARTIC WHITE,0041596020959,9ARCTIC WHITE FRESCO BOT.PLAS 3.79ML MP 004159...,1,LIQUIDO,CLORO,CLORO,OTR. TIPOS,CLORO,...,GERMICIDA,LIQUIDO,BLEACH,1,FABRIC TREATMENT AND SANIT,2024-01-02,NaN,NaN,NaN,NaN
2,ARTIC WHITE,ARTIC WHITE,0041596020959,9ARCTIC WHITE FRESCO BOT.PLAS 3.79ML MP 004159...,1,LIQUIDO,CLORO,CLORO,OTR. TIPOS,CLORO,...,MASCOTAS,LIQUIDO,BLEACH,1,FABRIC TREATMENT AND SANIT,2024-01-03,NaN,NaN,NaN,NaN
3,ARTIC WHITE,ARTIC WHITE,0041596020959,9ARCTIC WHITE FRESCO BOT.PLAS 3.79ML MP 004159...,1,LIQUIDO,CLORO,CLORO,OTR. TIPOS,CLORO,...,MULTIUSOS,GEL,BLEACH,1,FABRIC TREATMENT AND SANIT,2024-01-04,NaN,NaN,NaN,NaN
4,ARTIC WHITE,ARTIC WHITE,0041596020959,9ARCTIC WHITE FRESCO BOT.PLAS 3.79ML MP 004159...,1,LIQUIDO,CLORO,CLORO,OTR. TIPOS,CLORO,...,MULTIUSOS,LIQUIDO,BLEACH,1,FABRIC TREATMENT AND SANIT,2024-01-05,NaN,NaN,NaN,NaN

In [149]:
final.to_excel("consolidated_data.xlsx", index=False)
print("Archivo guardado como 'consolidated_data.xlsx'")

Archivo guardado como 'consolidated_data.xlsx'